# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - contextcheck
    - exhaustivestruct
    - golint
    - interfacer
    - lll
    - maligned
    - scopelint
    - varnamelen

linters-settings:
  varnamelen:
    ignore-decls:
      - l *Logger
      - l *rec.Logger
      - rw http.ResponseWriter
      - r *http.Request

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - exhaustivestruct
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - goerr113
        - gomnd
        - maintidx
        - noctx
        - varnamelen
