name: 'should-gitignore'

on: [push]

jobs:
  should-gitignore:
    name: Should gitignore
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: newtstat/github-actions-should-gitignore@v1.0.2
        #with:
        #  gitignores: 'path/to/.gitignore path/to/2/.gitignore'
